### ISSUE TITLE
Hi!!!!

### ISSUE THREAD

**Issue by ghost** [hrsetyono/pacific-atom#5]
Can you please ported this theme to Visual Studio Code I loved!!!

**Comment by hrsetyono** [comment]
Hi, I don't know what syntax Visual Studio uses, but I have Sublime and IntelliJ version that have more wide-used syntax

https://github.com/hrsetyono/pacific_intellij and https://github.com/hrsetyono/theme_pacific

Probably the sublime one will work after a bit of configuration. Thanks
